### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by scott87** [hamidzr/kodi-extras#3]
First of all thank you so much for your hard work.
Can you possibly give a breakdown of were to put these files on my raspberry pi. Running stretch. I have assistant running perfectly at the moment but would love to control kodi. Have never messed around with the assistant so this is new to me. A quick breakdown of were the files go and how to get it running thanks in advance. Sorry also for contacting you this way but cant find contact details elsewere.

Thanks in advance

**Comment by hamidzr** [comment]
I think we talked over skype. I'm closing this. reopen if you still have the issue
